- name: Example playbook
  hosts: all
  become: true

  tasks:
    - name: creating /etc/apt/keyrings folder
      ansible.builtin.file:
        path: /etc/apt/keyrings/
        owner: root
        group: root
        mode: '0755'
        state: directory

    - name: adding docker repository key
      ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes

    - name: adding docker repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian   bullseye stable'
        state: present

    - name: docker engine installation
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker
          - python3-docker

    - name: create container
      docker_container:
        name: postgrescontainer
        image: postgres:latest

    - name: create container
      docker_container:
        name: postgreslatest
        image: postgres:latest
        state: started
        env:
          POSTGRES_PASSWORD: mysecretpassword

